-- This testBench was generated by pyVhdl2Sch --
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_unsigned.all;


-- entity declaration
tb_InputGate IS
END tb_InputGate;

ARCHITECTURE behavior OF tb_InputGate IS
-- Component Declaration for the Unit Under Test (UUT)
COMPONENT InputGate
PORT (
Clk : IN clk;
PxClk : IN clk;
PxVal : IN classic;
a : IN classic;
b : IN classic;
c : IN classic;
d : IN classic;
daInOut!@g : INOUT classic;
PxValOut : OUT classic;
Lig : OUT classic;
Lig32 : OUT classic;
Col : OUT classic;
StatusInner : OUT classic;
FirstPass : OUT classic;
);
END COMPONENT;