-- This testBench was generated by pyVhdl2Sch --
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_unsigned.all;


-- entity declaration
ENTITY tb_ShiftRegister IS
END tb_ShiftRegister;

ARCHITECTURE behavior OF tb_ShiftRegister IS
-- Component Declaration for the Unit Under Test (UUT)
COMPONENT ShiftRegister
PORT (
    CLK : IN STD_LOGIC;
    Output : OUT MY_STD_LOGIC_VECTOR(0 downto 0)
);
END COMPONENT;
-- declare inputs and initialize them
    signal CLK : STD_LOGIC;
-- declare inouts and initialize them
-- declare outputs and initialize them
    signal Output : MY_STD_LOGIC_VECTOR(0 downto 0);
constant clk_period : time := 10 ns;

BEGIN
-- Instantiate the Unit Under Test (UUT)
uut: ShiftRegister PORT MAP (
    CLK => CLK,
    Output => Output
);
-- Clock process definitions( clock with 50% duty cycle is generated here.)
clk_process :process
begin
    <clk_a_remplacer> <= '0';
    wait for clk_period/2;  --for 5 ns signal is '0'.
    <clk_a_remplacer> <= '1';
    wait for clk_period/2;  --for 5 ns signal is '1'.
end process;
-- Stimulus process
stim_proc: process
begin
wait for 3*clk_period;
-- Insert your tests
   wait;
end process;
END;